### ISSUE TITLE
Use ExtensionLoader class

### ISSUE THREAD

**Issue by robincornett** [awesomemotive/edd-campaign-monitor#9]
Let's implement the EDD addon tools.

**Comment by robincornett** [comment]
@ashleyfae actually want to ask you about this--the only thing this would technically be needed for is the licensing initialization. Everything else in this extension is running on an edd hook or filter; there is no initialization function.

**Comment by ashleyfae** [comment]
If it weren't for our new licensing action hook in EDD core, I'd say we should use the loader just to initialize `EDD_License`.

But because of our new hook, I suppose it's not really needed.

However, because we won't use the loader, I have a thought for how I want to rework the licensing slightly. I'll do a PR just for that.

**Comment by ashleyfae** [comment]
Actually never mind. It was a stupid idea lolol.
